require 'rails_helper'

describe Datum, :type => :model do

  it "is generated by a component"
  it "has an attribute, category and value"
  it "belongs to an event"
  it "can be described as a JSON object"
end
