require 'rails_helper'

RSpec.describe Detail, :type => :model do
  pending "add some examples to (or delete) #{__FILE__}"

  it "is generated by a component"
  it "has an attribute, category and value"
  it "belongs to an event"
  it "can be described as a JSON object"  
end
